spring.application.name=soccerapp

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:soccerdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (browse to http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=none

# Load schema.sql on startup (data.sql replaced by DataLoader)
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# football-data.org API  (DO NOT COMMIT THIS KEY TO GIT)
football.api.url=https://api.football-data.org/v4
football.api.key=38eeb385a043413e93f3b604133b1fe3
